### ISSUE TITLE
xingyaopan解析出来的地址不可用

### ISSUE THREAD

**Issue by kkzzhizhou** [lzyAB/netdiskresolve#3]
`curl http://127.0.0.1:1306/resolve -X POST -d  '{"url": "http://www.xingyaopan.com/fs/56luuy69nueg7w7"}' --header "Content-Type: application/json"`
使用接口：api.ilzya.com:1306/resolve 会长时间卡住无法使用。

**Comment by lzyAB** [comment]
@kkzzhizhou  由于星耀盘会员账号问题，可能会有时间失效，不久就会恢复
